name: LaTeX Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run gen.sh script
      run: |
        chmod +x Reports/Latex/gen.sh
        ./Reports/Latex/gen.sh

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: KECReport
        path: Reports/Latex/KECReport.pdf

